package costaber.com.github.omniflow.cloud.provider.aws

const val AMAZON_COMMENT = "\"Comment\""
const val AMAZON_START_AT = "\"StartAt\""
const val AMAZON_STATES = "\"States\""
const val AMAZON_TYPE = "\"Type\""
const val AMAZON_TASK_TYPE = "$AMAZON_TYPE: \"Task\","
const val AMAZON_PASS_TYPE = "$AMAZON_TYPE: \"Pass\","
const val AMAZON_RESOURCE = "\"Resource\": \"arn:aws:states:::apigateway:invoke\","
const val AMAZON_INPUT_PATH = "\"InputPath\": "
const val AMAZON_PARAMETERS = "\"Parameters\": {"
const val AMAZON_API_ENDPOINT = "\"ApiEndpoint\": "
const val AMAZON_METHOD = "\"Method\": "
const val AMAZON_PATH = "\"Path\": "
const val AMAZON_QUERY_PARAMETERS = "\"QueryParameters\": {"
const val AMAZON_AUTH_TYPE = "\"AuthType\": "
const val AMAZON_RESULT_SELECTOR = "\"ResultSelector\": {"
const val AMAZON_RESULT_PATH = "\"ResultPath\": "
const val AMAZON_RESPONSE_BODY = "ResponseBody"
const val AMAZON_END = "\"End\": true"
const val AMAZON_NEXT = "\"Next\": "